---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8088
      TORRENTING_PORT: 6881
    volumes:
      - /home/vytor/apps/qbittorrent:/config
      - /media/media:/data
    ports:
      - "8088:8088"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${FLARESOLVERR_LOG_LEVEL:-info}
      TZ: ${TZ}
    networks:
      - media

networks:
  media:
    external: true
