services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "7070:8000"
    volumes:
      - /home/vytor/apps/paperless/data:/usr/src/paperless/data
      - /home/vytor/apps/paperless/media:/usr/src/paperless/media
      - /home/vytor/apps/paperless/export:/usr/src/paperless/export
      - /home/vytor/apps/paperless/inbox:/usr/src/paperless/consume
      - /home/vytor/apps/paperless/languages/por.traineddata:/usr/share/tesseract-ocr/5/tessdata/por.traineddata
    env_file:
      - ./.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_OCR_LANGUAGE: por
      PAPERLESS_OCR_LANGUAGES: por
volumes:
  redisdata:
