services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - 127.0.0.1:3001:3000
    env_file:
      - ./.env
    environment: # Defaults are listed below. All are optional.
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - HTTP_ALLOWED=false # setting this to true is unsafe, only set this to true locally
      - ALLOW_UNAUTHENTICATED=true # allows anyone to use the service without logging in, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=24 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
    volumes:
      - /home/vytor/apps/convertx:/app/data
